FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY ["CorinthiansApi.csproj", "./"]

RUN dotnet restore "CorinthiansApi.csproj"

COPY . .

RUN dotnet publish "CorinthiansApi.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

# Garante que o JSON esteja disponível no container
COPY --from=build /src/Data ./Data

ENV ASPNETCORE_URLS=http://+:80

EXPOSE 80

ENTRYPOINT ["dotnet", "CorinthiansApi.dll"]
